CREATE TABLE [CURSO] (
  [Codigo] VARCHAR(50) PRIMARY KEY,
  [Nombre] VARCHAR(50) NOT NULL,
  [Carrera] VARCHAR(50) NOT NULL,
  [Habilitado] BIT NOT NULL
)
GO

CREATE TABLE [SEMESTRE] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Anio] INT NOT NULL,
  [Id_periodo] INT NOT NULL
)
GO

CREATE TABLE [CURSO_SEMESTRE] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Id_curso] VARCHAR(50) NOT NULL,
  [Id_semestre] INT NOT NULL
)
GO

CREATE TABLE [PERIODO] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Nombre] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [NOTICIA] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Titulo] VARCHAR(100) NOT NULL,
  [Mensaje] VARCHAR(200) NOT NULL,
  [Fecha_publicacion] DATE NOT NULL,
  [Autor] VARCHAR(50) NOT NULL,
  [Id_grupo] INT NOT NULL
)
GO

CREATE TABLE [GRUPO] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Numero] INT NOT NULL,
  [Id_curso] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [GRUPO_PROFESOR] (
  [Numero_Grupo] INT,
  [Profesor] VARCHAR(50),
  PRIMARY KEY ([Numero_Grupo], [Profesor])
)
GO

CREATE TABLE [GRUPO_ESTUDIANTE] (
  [Numero_Grupo] INT,
  [Estudiante] VARCHAR(50),
  PRIMARY KEY ([Numero_Grupo], [Estudiante])
)
GO

CREATE TABLE [RUBRO] (
  [Nombre] VARCHAR(50) PRIMARY KEY,
  [Porcentaje] DECIMAL(5, 2) NOT NULL,
  [Id_grupo] INT NOT NULL
)
GO

CREATE TABLE [EVALUACION] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Es_individual] BIT NOT NULL,
  [Notas_publicadas] BIT NOT NULL,
  [Peso] INT NOT NULL,
  [Fecha_entrega] DATE NOT NULL,
  [Hora_entrega] TIME NOT NULL,
  [Id_rubro] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE [EVALUACION_INTEGRANTES] (
  [Id_evaluacion] INT,
  [Estudiante] VARCHAR(50),
  PRIMARY KEY ([Id_evaluacion], [Estudiante])
)
GO

CREATE TABLE [EVALUACION_ESPECIFICACION] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Id_evaluacion] INT NOT NULL,
  [Id_especificacion] INT NOT NULL
)
GO

CREATE TABLE [ENTREGABLE_ARCHIVO] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Id_entregable] INT NOT NULL,
  [Id_archivo] INT NOT NULL
)
GO

CREATE TABLE [ENTREGABLE_ARCHIVO_DETALLE] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Id_entregable] INT NOT NULL,
  [Id_archivo_detalle] INT NOT NULL
)
GO

CREATE TABLE [CARPETA] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Nombre] VARCHAR(100) NOT NULL,
  [Solo_lectura] BIT NOT NULL,
  [Ruta] VARCHAR(50) NOT NULL,
  [Id_grupo] INT NOT NULL
)
GO

CREATE TABLE [ARCHIVO] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Fecha_creacion] DATE NOT NULL,
  [Nombre] VARCHAR(50) NOT NULL,
  [Tamanio] DECIMAL(8, 2) NOT NULL,
  [Id_carpeta] INT NOT NULL
)
GO

CREATE TABLE [ENTREGABLE] (
  [Id] INT PRIMARY KEY IDENTITY(1, 1),
  [Observaciones] VARCHAR(50) NOT NULL,
  [Estudiante] VARCHAR(50) NOT NULL,
  [Id_evaluacion] INT NOT NULL
)
GO

ALTER TABLE [SEMESTRE] ADD FOREIGN KEY ([Id_periodo]) REFERENCES [PERIODO] ([Id])
GO

ALTER TABLE [CURSO_SEMESTRE] ADD FOREIGN KEY ([Id_curso]) REFERENCES [CURSO] ([Codigo])
GO

ALTER TABLE [CURSO_SEMESTRE] ADD FOREIGN KEY ([Id_semestre]) REFERENCES [SEMESTRE] ([Id])
GO

ALTER TABLE [NOTICIA] ADD FOREIGN KEY ([Id_grupo]) REFERENCES [GRUPO] ([Id])
GO

ALTER TABLE [GRUPO] ADD FOREIGN KEY ([Id_curso]) REFERENCES [CURSO] ([Codigo])
GO

ALTER TABLE [GRUPO_PROFESOR] ADD FOREIGN KEY ([Numero_Grupo]) REFERENCES [GRUPO] ([Id])
GO

ALTER TABLE [GRUPO_ESTUDIANTE] ADD FOREIGN KEY ([Numero_Grupo]) REFERENCES [GRUPO] ([Id])
GO

ALTER TABLE [RUBRO] ADD FOREIGN KEY ([Id_grupo]) REFERENCES [GRUPO] ([Id])
GO

ALTER TABLE [EVALUACION] ADD FOREIGN KEY ([Id_rubro]) REFERENCES [RUBRO] ([Nombre])
GO

ALTER TABLE [EVALUACION_INTEGRANTES] ADD FOREIGN KEY ([Id_evaluacion]) REFERENCES [EVALUACION] ([Id])
GO

ALTER TABLE [EVALUACION_ESPECIFICACION] ADD FOREIGN KEY ([Id_evaluacion]) REFERENCES [EVALUACION] ([Id])
GO

ALTER TABLE [EVALUACION_ESPECIFICACION] ADD FOREIGN KEY ([Id_especificacion]) REFERENCES [ARCHIVO] ([Id])
GO

ALTER TABLE [ENTREGABLE_ARCHIVO] ADD FOREIGN KEY ([Id_entregable]) REFERENCES [ENTREGABLE] ([Id])
GO

ALTER TABLE [ENTREGABLE_ARCHIVO] ADD FOREIGN KEY ([Id_archivo]) REFERENCES [ARCHIVO] ([Id])
GO

ALTER TABLE [ENTREGABLE_ARCHIVO_DETALLE] ADD FOREIGN KEY ([Id_entregable]) REFERENCES [ENTREGABLE] ([Id])
GO

ALTER TABLE [ENTREGABLE_ARCHIVO_DETALLE] ADD FOREIGN KEY ([Id_archivo_detalle]) REFERENCES [ARCHIVO] ([Id])
GO

ALTER TABLE [CARPETA] ADD FOREIGN KEY ([Id_grupo]) REFERENCES [GRUPO] ([Id])
GO

ALTER TABLE [ARCHIVO] ADD FOREIGN KEY ([Id_carpeta]) REFERENCES [CARPETA] ([Id])
GO

ALTER TABLE [ENTREGABLE] ADD FOREIGN KEY ([Id_evaluacion]) REFERENCES [EVALUACION] ([Id])
GO

